language: node_js
node_js:
- stable
script:
- npm run lint
- npm run test
- npm run coverage

addons:
    code_climate:
        repo_token: jtsKnW+cy9gQlOmlHe/iuDclycXITy/lsJIBgVIql+WN0LP3ULm7hiwgQKIKQwMba18U88WlhJAy60GvYysht9BrGbv5i5h0lwxrOyv69IIszo6tsVkVoi762eeKvfk4GaL7W0Uy14Az1qzIMFHFnsTfghimID+CzZIkQVxdA1xFEkGrJ38cS4HMgZTwL8f+D6iLYRtCTCbDZiXMS9Kxw3NzQ7dq/aLyhRwrfWGYCjyE3C2YlD7pY3NspUnCgXJ8YkCjZWHqTEnxo9Aj6Ps4y4SNNNH54JgCZf26Nzjggr4je1l8ru583xewdcTYh/UOpp7gUwQ5ZPPz46HGcrdyBtzOMv8DPyYHXCLUHcl96RVavV71/jzUV58dxwCBxFaXTigz2yjV37DOwkh9+5f+yt9uqVpm3msvMuchg9xUkZgK/byq65wklqvhE8cePNGPAtT+PxVvws8L5fYATPr87NP49GtO4ffG7rHmqhQLIx1tauaMBJnhPm2mnOfu8sDJX5RMQ8GHON5ueic/3ZVQ6zEjKds5Yh8aH6HfvsZb9cly6Xv0OMsfnZZUq1boNQFpSY9iy1mjOBcTHgQPeAsoJwUQmaaurtRpPIL17lBQa36jhNVyMuNU8WhHh5rLtKklfSYa3O5KGdv+cTPzRzkNZpZslf36i1FHOMHdIgxqClA=
    coveralls:
        repo_token: hBJRdwL4ZjA5gEavLrO1BB2xMPih0UuRwmd9W8BA+WwAWTl+5K+h2mBd7XngXIFk4oXIg2q5OmWSu7V/Qtwf1wsbroQWtTcRmEHm/V6tswuH1z3Il8XtPer1g0ruoj0sdwFYWUC0c1nnM1IK3I1sPLB/xaUKf4lYM3ZS3lVU3nAFjqNNhQJ4sTWEWcPvlkec5dsx71FRmw5RA6HCtnqC/wbU0GU9QRrl2kOLf+LkjNninkHfPlIQMNpKQpht5yjxTY7Lo7v4rFqj8f+Rn0kbQPTV3JaZ9iKeTwOX/lZN2mxhFAbwaKMmIueTlDdJa5nhr9UhaMiU1uOmBa9x+hZvlEN8qar7bORRyT6PSEC9cb1aMQ38jP52f+u99ZOFoejk16oYIy5mPZPH9qXxPiJGHwkhiG/9sQMQUjg6KrGwoi8WWYxSTnRck9UKoinJ9U2Nmsk2YdfGR6k2jXYfJS4p56YwvA/L/7fzRQwTEOK89QxpuSFJsCx8pPCg1+uvQ0nfxo7Lx76o4S10NySscNUqwCh5H8ScmyPq55+BS1Am2LpbgkDU3aOzqkDbPrue53SuefDCOJGN+XWSjTJzWyz/TCrcY9XavbrPqicHtYRVV7IHnXfBtjUYq0V6fm64P1AB4OkT6yMBYO8R57dO3qF0+tYt/FzQUrrCszza79zQgqI=
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

deploy:
  provider: heroku
  api_key:
    secure: ZSQj46Kmn+H7QzkzXCRC0UhL71G+5u/ggFLfoe0MwiIJ5Z2TlqjPG/tPLdJw6QwI3IwoKt5KyHutei1tuFSwogwWwuHGliiFN4iDmfBsUK1Xv+q5yriOVyZLdSPNs4UHb0fPNGwSZN3eESLiCui+tGMapxppJuXDjAHjJNCRiBr9cumcI6Z2ra8pLXZsi24sIhAO4J9N+HoIoloxPQGk+Ix+X6ezD9mJHKaDli267O8bde/lDt1Pg43LvhL85/rp0dgxjIkOpf4RHB+GwwcaeiljWgeVoLPy0BmyWnJ8160/qmVugmuHR3ABKbZvyqmDL3T9D0QGIRRDzOxZVGh2L5dAQe8wOXKl68BWs6HLBz9aX8i7NEw3IHdnsowWg69X5BEkTxqL1+zNWnqRRTnRpKV4vueR/k81wHPDd7O5B6KBmw1lAdHW7rtybhI8WzdVF4MTy1g1llPGfvBH01udh9F0j9lWXH3JXpqGJxmen3JzYWXn1X1Wap4jZc7TMkO4zjxoy9Br0heFV/fgwHAF7AgNr2Waq+9SDnTwFVtAzTvHbJfb39q/YJvl8Nr/SpfRlqg7WRp852K54XdrVgrUy9SjsW3JfW8e5ldvvu/ryWJTET+wrjT42QGPkffelzVL7g0cTLGHW1T+EKkPeBKuyrwNCEuZzhtYcrVO9oE39eI=
  app: timothy-i-reporter
  on:
    repo: TimothyMee/i-reporter

after_success:
- npm run coveralls