language: node_js
node_js:
- 10.10.0
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: NRrAfghGJo8aBlwjkgdKuhB6T6+A0gdFb7XMJrDgPauR4wQRMVLAgPekhS8ZOWcnMwML6gvOu+ua3fXlLEYWgDbbrQvd50nz9NMC2Jqw9Z4i45QTR5buNinXQ99nyOkEw+Wi12yMj/wf8hFv81uq8eENZAdAwiqPEMah34iQK8j0VbuVw2ZwFaXZD8iFZVMwhxQv6gKv+C2yH4C2FfB9iksIZQXzpYln2ArL2/ri+ToGQ4wa8etrm4aCKehtzB/LSQUzaHXVExS+eyNv/8VmQsRxx3nXMbXb6+kLPalLHpl2YQzCVg9+V+U6CyX8KaWp8SAXjPqQl3DJMT0Jg6d61os3vwlE49h8V2agB1nQhsiUgrCBhDREO6SYDX4burxROSuRYoZEYao427QsdxAzxK0m40ppoql1fjYn40L++WZYxszNUXOIvDYMGKFu+nTj6ILMMD1YNL5J8OBYGr9adWw9XlP6EM/iSGZeBrpzARTJMxmWD1DbxpKE1WI5hanPMiPYIvbyz9BQ70almmTNOmVgNDn4sHBkDX/jAxdZgTZg8OKge1YQ4pFODu2djkmsAtuArdKNCTWobtlE1NcJFU0nkyk61dITt49px7UiFBwTTqfAycVBX+Q/MtNqdveIhEMaIBu3z23rY8yS7MC+96TizwSCjZUsFMV8TYQRFVw=
  app: timothy-i-reporter
  on:
    repo: TimothyMee/i-reporter
  script:
  - node index.js