language: node_js
node_js:
  - 10.10.0
script:
  - "npm run lint"
  - "npm run test"

deploy:
  provider: heroku
  api_key:
    secure: 2b175d52-ce57-4ab5-98e5-c16d2d6da047
  app: timothy-i-reporter
  on:
    repo: TimothyMee/i-reporter
